### ISSUE TITLE
REPLACE( ) is not working in WHERE condition in version 1.7.3

### ISSUE THREAD

**Issue by pradeep-nagarajan** [AlaSQL/alasql#1455]
We are getting below exception for **WHERE REPLACE(metaData->field1,"arc","")  = "test"**

TypeError: (A || "").split is not a function
    at Object.D.REPLACE (webpack-loader.js:2:352024)
    at s.Query.eval [as wherefn] (eval at E.Select.compileWhere (webpack-loader.js:2:316925), <anonymous>:3:1671)
    at Bt (webpack-loader.js:2:290783)
    at Bt (webpack-loader.js:2:291572)
    at c (webpack-loader.js:2:290761)
    at r (webpack-loader.js:2:290608)
    at Object.eval [as datafn] (eval at <anonymous> (webpack-loader.js:2:309928), <anonymous>:3:57)
    at webpack-loader.js:2:306365
    at Array.forEach (<anonymous>)
    at webpack-loader.js:2:306312

**Comment by soundarrajan-official** [comment]
I am interested to solve this issue, so can you please assign me for this issue ?

**Comment by mathiasrw** [comment]
Sure. Thank you.

**Comment by mathiasrw** [comment]
@soundarrajan-official  Are you able to make a test that confirmes this?

**Comment by ambujsahu81** [comment]
Hi @mathiasrw , I wanted to work on this issue but i am failing to make valid test which can result in the exception mentioned in the issue.

I tried something like this and it worked fine:
```js
var dataArray = [ 
    { id: 1, metaData: {field: "Testarc"} }, 
    { id: 2, metaData: {field: "TestGrc"} }, 
    { id: 3, metaData: {field: "arcTest"} }, 
    { id: 4, metaData: {field: "Test"}},
    { id: 5, metaData: {field: "Tarcest"}},
    { id: 6, metaData: {field: "TarcGest"}},
   ];

console.log(alasql('SELECT id FROM ? WHERE REPLACE(metaData->field, "arc", "") = "Test"', [dataArray]));
// output: [ { id: 1 }, { id: 3 }, { id: 4 }, { id: 5 } ] this is the correct result.
```

**Comment by yugkhokhar** [comment]
I would to like to work on this issue

**Comment by yugkhokhar** [comment]
Sure, I will work on it and give you update about it

**Comment by mathiasrw** [comment]
How are you going @yugkhokhar ?

**Comment by NmN03jain** [comment]
can i work on this issue ?

**Comment by NmN03jain** [comment]
Thanks for this opportunity, can you help me  how to find this issue in code base.

**Comment by mathiasrw** [comment]
@NmN03jain Looks like this place


<img width="620" alt="image" src="https://github.com/AlaSQL/alasql/assets/1063454/9eb09e89-e279-47cd-ba50-78be603aa077">

It might just need a .toString() on target - but it would be good to add a test to replicate this and then confirm that its all fixed.

**Comment by NmN03jain** [comment]
Ok thanks for the help I'll try my best

**Comment by NmN03jain** [comment]
@mathiasrw i've made the changes and commited to my fork but i think there is some issue while pull request, so pls check there is some problem in image or my pull request is done successfully .
![Screenshot (28)](https://github.com/AlaSQL/alasql/assets/90062260/abd103d9-2b70-473a-925e-a9b1bc881c93)

**Comment by mathiasrw** [comment]
This is as intended - as only the maintainers should be able to merge it. The PR is fine.

**Comment by mathiasrw** [comment]
Fix released in v4.11.0
